[package]
name = "replication_groups"
version = "0.25.5"
edition = "2021"
publish = false

[dependencies]
bevy = { workspace = true, features = [
  "bevy_gizmos",
  "bevy_sprite",
  "bevy_sprite_render",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_winit",
  "bevy_window",
  "bevy_ui",
  "bevy_text",
  "default_font",
  "png",
  "x11",
] }
lightyear = { path = "../../lightyear", features = ["server", "client", "udp", "webtransport", "websocket", "netcode", "input_native", "debug"] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "replication_groups"
path = "src/main.rs"
