[package]
name = "multi_transport_avian_3d_character"
version = "0.25.5"
rust-version.workspace = true
edition.workspace = true
publish = false

[features]
default = ["server", "client"]
server = ["lightyear/server"]
client = ["lightyear/client"]

[dependencies]
bevy = { workspace = true, features = [
    "bevy_gizmos",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_winit",
    "bevy_window",
    "bevy_ui",
    "bevy_text",
    "bevy_pbr",
    "default_font",
    "png",
    "x11",
] }
lightyear = { path = "../../lightyear", features = [
    "std",
    "server",
    "client",
    "netcode",
    "udp",
    "webtransport",
    "websocket",
    "interpolation",
    "prediction",
    "replication",
    "leafwing",
    "avian3d",
    "debug",
] }
lightyear_avian3d = { path = "../../lightyear_avian3d", features = ["3d"] }
avian3d = { workspace = true, features = [
    "3d",
    "f32",
    "parry-f32",
    "parallel",
    "serialize",
] }
leafwing-input-manager = { workspace = true, default-features = false, features = [
    "keyboard",
] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
rand.workspace = true

[lints]
workspace = true
